### ISSUE TITLE
AddSynchronizationNodes() adds new nodes even if MinimumDeltaDistance is not reached

### ISSUE THREAD

**Issue by Crashthatch** [mapbox/mapbox-arkit-unity#16]
[AddSynchronizationNodes()](https://github.com/mapbox/mapbox-arkit-unity/blob/3f813b076037f10fab401f836438a2c3c9d83bd1/Assets/Mapbox/Unity/Ar/SimpleAutomaticSynchronizationContext.cs#L70) always adds to _gpsNodes / _arNodes, even if the distance travelled during this location-update is < MinimumDeltaDistance. Since the calculation in ComputeAlignment() uses the difference between the last 2 added _gpsNodes, it could calculate the alignment based on very small movements (that MinimumDeltaDistance is designed to avoid).

- Imagine situation where MinimumDeltaDistance is set to 10m.
- The devices moves 9.9m east, so the GPS and LocationService both adjust accordingly, and [_arDelta & _gpsDelta are incremented by 9.9](https://github.com/mapbox/mapbox-arkit-unity/blob/3f813b076037f10fab401f836438a2c3c9d83bd1/Assets/Mapbox/Unity/Ar/SimpleAutomaticSynchronizationContext.cs#L83)
- 9.9 < 10.0, so AddSynchronizationNodes exits early and does not call ComputeAlignment().
- Now the device moves 0.2m west (back the way it came), but the GPS is slightly inaccurate and registers a further small movement east 0.2m
- _arDelta and _gpsDelta are increased to 10.1m (> MinimumDeltaDistance), so ComputeAlignment() is called, but _currentArVector = (-0.2,0,0) and _currentAbsoluteGpsVector = (0.2,0,0), so rotation=180 (incorrect)

I would suggest that ComputeAlignment() should be considering the sum of all movements since the last ComputeAlignment call (ie. 9.9+0.2 vs 9.9-0.2) to compute the rotation. I think this can be achieved by removing _arDelta completely, and making _currentArVector a "running total" of the new location vectors until _currentArVector.magnitude > MinimumDeltaDistance, at which point ComputeAlignment() would be called (and similar for _currentAbsoluteGpsVector).

Do you agree, or have I misunderstood somewhere?

**Comment by david-rhodes** [comment]
@Crashthatch You deserve a 🍪! You're absolutely correct, and this explains why I've occasionally seen some odd behavior. Thank you for posting your find! I'd love to fix this, but I may not get to it for a while (busy with some other tasks). That said, we would gladly accept a pull request if you want to fork this repo! 😄

**Comment by Crashthatch** [comment]
:cookie: nom nom.

I'll do a PR tomorrow. I see the README refers to some unit tests, but I can't seem to find them? I only see test files for the mapbox SDK itself, not the AR extensions?

**Comment by david-rhodes** [comment]
Ah, I actually removed the tests and need to update the README. You can ignore those for now--thanks for checking!
