### ISSUE TITLE
ARC Semantic Issues

### ISSUE THREAD

**Issue by edwardrmiller** [mapbox/mapbox-arkit-unity#2]
I'm getting several ARC semantic issues including:

"No visible @interface for 'ARCamera' declares the selector 'projectionMatrixWithViewportSize:orientation:zNear:zFar:'

"No visible @interface for 'ARCamera' declares the selector 'projectionMatrixWithViewportSize:orientation:zNear:zFar:'"

and

"No visible @interface for 'ARFrame' declares the selector 'displayTransformWithViewportSize:orientation:'

Any idea why?

**Comment by UnityEQ** [comment]
Had same problem, this was my workaround:
https://forum.unity.com/threads/arkit-support-for-ios-via-unity-arkit-plugin.474385/page-19#post-3176004

**Comment by david-rhodes** [comment]
@UnityEQ Thanks for the reply! Yep, things with ARKit were moving quickly in beta. Now that iOS 11 is officially released, this library will be updated soon to reflect official releases (and hopefully it doesn't break as often). 😏
