### ISSUE TITLE
Fix ping-ponging map position

### ISSUE THREAD

**Issue by david-rhodes** [mapbox/mapbox-arkit-unity#21]
With the map camera active, you may notice the AR path crossing back and forth over the GPS path.

This is caused by `AverageHeadingAlignmentStrategy`. My guess is somewhere in undoing the original rotation and applying the new rotation: https://github.com/mapbox/mapbox-ar-unity/blob/develop/Assets/Mapbox/Unity/Ar/AverageHeadingAlignmentStrategy.cs#L60.

In the meantime, use a different strategy (`snap`).

**Comment by wilhelmberg** [comment]
Should have been fixed by #19
#19 also comes with tests #34 

Going to reopen if we should see this issue again.
