### ISSUE TITLE
World scale ar experience demo

### ISSUE THREAD

**Issue by ivanhoCP** [mapbox/mapbox-arkit-unity#22]
May I know whether there is a demo scene refer to the reference video?
(World scale ar  with pathfinding, direction arrow display etc.)

**Comment by david-rhodes** [comment]
The project referenced in the Unite Austin talk is not yet public. However, we offer directions (navigation) examples in the base Mapbox SDK (`Drive.unity` scene). Combined with this library, you should be able to easily create a world-scale AR scene for navigation.

**Comment by rslevin** [comment]
Hey David, Yeah would this would be something that would interest us too, is there any plans to make it public as an example, similar to the Mapbox SDK examples?

**Comment by david-rhodes** [comment]
@ivanhoCP @rslevin What aspects of the demo are you most interested in? Perhaps we can make a "lite" version. The concern is that the demo project was a prototype and contains some ugly code/hacks. 😄

**Comment by smtabatabaie** [comment]
Hi David , Yes I agree it will be great if we can have a simple example of that project. By the way it was great in the video :)

**Comment by leonard2014** [comment]
Hey David,

Yes it will be greatly helpful if the source code of ar navigation demo in the Unite Austin video is public. It is totally acceptable no matter how ugly the code/hack is. Thanks!

**Comment by sampin** [comment]
PLease help me with the source code for unity, we really like in the way it is, pleaseeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee

**Comment by aadimator** [comment]
Even with the hacks, it'll prove to be really useful for us as we'll better be able to see the current technological limitations and some workarounds/hacks to overcome those.

**Comment by david-rhodes** [comment]
I'm trying to get some time today to package this up. Thanks for all the requests!

**Comment by david-rhodes** [comment]
Package complete--should be uploaded soon!

**Comment by sampin** [comment]
Hi David can you share package today please, we really need it

**Comment by rslevin** [comment]
Hey @david-rhodes - Once its uploaded (or if its currently uploaded) Please let us know when and where we can find it. Cheers!

**Comment by sampin** [comment]
Hi David please help us with sample code

**Comment by Astro-no-mic** [comment]
Hi @david-rhodes - my team is also interested in looking at the Unite Austin demo. In particular how to use this sdk to do the transition from table-top view to real-world view.

I apologize for being fairly new to Unity and Mapbox, and have next to no idea how to use this sdk just from the example scene provided. It would be really helpful if there was something like a simple tutorial on how to use this sdk to place objects in the real world or how to get started on making something like the Unite Austin demo. Thanks!

**Comment by doerrdude** [comment]
Hi @Astro-no-mic, the Austin demo is not yet public, but for reference you can check out the [AR Repo](https://github.com/mapbox/mapbox-ar-unity) for a tabletop example. Also, here is a step-by-step [tutorial](https://blog.mapbox.com/placing-ar-portals-all-over-the-world-pt-2-1470b0f70281) how to populate parks with NPC's in world-scale AR using Mapbox Unity SDK.

**Comment by david-rhodes** [comment]
Hey @Astro-no-mic, my solution to transition from tabletop to world-scale was literally to scale the map root transform about the "player" position in local map space. The code itself was quite messy, but you just convert your lat/lon to Vector3 (using the convenience method that now lives in `AbstractMap`) and scale about that position (taking into account your AR drop location offset, of course). Does that make sense?

**Comment by diegoarx** [comment]
david-rhodes, there is no Drive.unity scene in the actual mapbox sdk

**Comment by david-rhodes** [comment]
@diegoarx A directions example can now be found in the interactive vector map example scene.

**Comment by 0xandrei95** [comment]
@david-rhodes any update on the upload? It has been 2 months since Package Complete.

**Comment by smtabatabaie** [comment]
@david-rhodes Hi David, Is the new www.mapbox.com/AR the same as this project? Thanks

**Comment by wilhelmberg** [comment]
@smtabatabaie almost, soon this repo is going to be merged into https://github.com/mapbox/mapbox-unity-sdk
Then those two will be the same.

**Comment by ShuchangXu** [comment]
Hi @lauri-rustanius The table top AR repo link you posted is 404 not found now. Could you provide the new link?

**Comment by ShuchangXu** [comment]
@david-rhodes  Has the Unite Austin Demo package been uploaded? I would really appreciate it if you can provide the demo for learning. Thanks!

**Comment by wilhelmberg** [comment]
@ShuchangXu 
> The table top AR repo link you posted is 404 not found now. Could you provide the new link?

This branch has been merged into the main branch (`develop`).
If you just clone the repo you get the tabletop example.

**Comment by doerrdude** [comment]
@ShuchangXu here is the new link https://github.com/mapbox/mapbox-ar-unity :)

**Comment by 0xandrei95** [comment]
@david-rhodes, are you going to upload the Unite Austin Demo or let us keep asking about it for another couple of months?
At least give us a time frame.
This lack of action is very unpleasant, mate.

**Comment by wilhelmberg** [comment]
Sorry for the inconvenience but currently there are no plans to provide the Austin demo as it was a one off and it is not being maintained.

**Please note that this repository is going to be merged into the main [`mapbox-unity-sdk`](https://github.com/mapbox/mapbox-unity-sdk/) during the next days.**

If you have any specific questions about the SDK or AR please open an issue there
https://github.com/mapbox/mapbox-unity-sdk/issues/new
and tag it with the `AR` label if appropriate.

Thank you for your understanding.

**Comment by apavani** [comment]
@iAeneas [Here's a link](https://s3.amazonaws.com/mapbox-unity-sdk/examples/TripPannerDemo.zip) to the project. We removed the assets that prevented us from posting it earlier. But here you go!

**Comment by ShuchangXu** [comment]
@apavani Thanks for open-sourcing! Great for learning!

**Comment by 0xandrei95** [comment]
@apavani Big thanks,mate. Much appreciated. Cheers!

**Comment by ShuchangXu** [comment]
@iAeneas @apavani  Hello I tried out the Unite Austin Demo but got stuck at the search(geocoding) stage. I placed the map on TableTop and typed some place in the map. But always returns "No results found."  I checked the

**Comment by ShuchangXu** [comment]
@iAeneas @apavani Hello! I tried out the Unite Austin Demo but got stuck at the search(geocoding) stage. 
I placed the map on TableTop and typed some place in the range of the map. But it always returns "No results found".
To solve it, I first checked the [geocoding API](https://www.mapbox.com/mapbox-unity-sdk/api/mapbox-sdk-cs/Mapbox.Geocoding.ForwardGeocodeResource.html) and changed Country, AutoComplete but it doesn't work. I'm in China so I tried both English and Chinese as keywords. Still not found. But I can find the name in [the Geocoding demo](https://www.mapbox.com/api-playground/#/?_k=zwd9pr).
Besides, I thought it might have something to do with the 3D Map and Bbox. But I tried to print Bbox and it seems no problem.
I was just stuck here and tried solutions I can think of. Has this problem ever came up to you? And how did you manage it? Thanks!

**Comment by nikhilsawlani** [comment]
@apavani @ShuchangXu  hey! even I'm getting the same problem that it cannot find places I'm from India did anyone resolved the error.

**Comment by apavani** [comment]
@nikhilsawlani Thanks for trying our project out. We have a much different workflow now with the new version of our SDK. If you would like to port that project to use our latest version from the develop branch from [here](https://github.com/mapbox/mapbox-unity-sdk), we can support you better. Porting to 1.4 may cause many things to break. So, it is highly recommended that you back up any work you've done already before you start integrating our new SDK.
