### ISSUE TITLE
Use Alignment for ARInterface, rather than transforming Map Root

### ISSUE THREAD

**Issue by david-rhodes** [mapbox/mapbox-arkit-unity#24]
Reference: https://blogs.unity3d.com/2017/11/16/dealing-with-scale-in-ar/

#### TL;DR
We can use ARInterface to compute camera offsets such that our camera rig can be moved/rotated, rather than our map. This should simplify several things!

**Comment by wilhelmberg** [comment]
continued at https://github.com/mapbox/mapbox-unity-sdk/issues/555
