### ISSUE TITLE
Investigate using a lookup table + constants to assist with drift.

### ISSUE THREAD

**Issue by david-rhodes** [mapbox/mapbox-arkit-unity#26]
Capture drift values in varying environments (lighting scenarios, walking speed, surface type or feature count, etc.). Measure AR camera movement delta over a fixed distance several times to ensure drift is, in fact, relatively static. 

In doing so, we may be able to compensate for at least some amount of drift.

**Comment by diegoarx** [comment]
The drift is when you place an object in a lat/long and looks wrong but when you move to it starts moving bit a bit to the right location?

**Comment by david-rhodes** [comment]
@diegoarx No, drift is the AR localization recording only 40 meters moved through space when in actuality you moved 50 meters. There are several factors for this (lack of tracking points, moving too fast, bad lighting, etc.).

**Comment by wilhelmberg** [comment]
continued at https://github.com/mapbox/mapbox-unity-sdk/issues/557
