### ISSUE TITLE
Use compass for initial alignment

### ISSUE THREAD

**Issue by david-rhodes** [mapbox/mapbox-arkit-unity#27]
Even though the compass is generally unreliable, we could use it for an initial alignment. 30% success is better than 0%.

**Comment by diegoarx** [comment]
This is what i need, when the ar camera starts is in the wrong orientation, but there is no way to have a 100% success to know where north is?

**Comment by MiroMuse** [comment]
@diegoarx we're working on creating a solution for that problem. Stay tuned:)

**Comment by wilhelmberg** [comment]
continued at https://github.com/mapbox/mapbox-unity-sdk/issues/559
