### ISSUE TITLE
Create a basic UX to encourage proper calibration

### ISSUE THREAD

**Issue by david-rhodes** [mapbox/mapbox-arkit-unity#29]
For example: one developer created some cubes (arranged in a line) in front of the camera that the user should walk through. These were placed just a short distance apart. The location provider minimum distance update can be lowered to help provide several updates in just a short distance walked.

- Encourage user to walk in straight line
- Give them visual targets
- Text to encourage movement and provide context for why
- Lower location update threshold temporarily (may not work in low accuracy environments)
- Automatic sync implementation may also need it's min distance lowered.

**Comment by diegoarx** [comment]
What is the reason for the user to walk through a line?

**Comment by wilhelmberg** [comment]
Automatic synchronization of GPS and AR position.

**Comment by david-rhodes** [comment]
To compute a more accurate heading than what the device compass would normally provide.

**Comment by wilhelmberg** [comment]
continued at https://github.com/mapbox/mapbox-unity-sdk/issues/560
