### ISSUE TITLE
xcode (9A235) build errors

### ISSUE THREAD

**Issue by janvdh1111** [mapbox/mapbox-arkit-unity#3]
Hi!
Thanks for the awesome project, but I can't get it to build correctly on xcode..
It gives me a bunch of errors..
Do you have a solution for this?

Thanks!
Here are some of the errors:

Users/Jan/AR_GPS/Builds/PrevizAR_v00/Libraries/UnityARKitPlugin/Plugins/iOS/UnityARKit/NativeInterface/ARSessionNative.mm:689:5: error: unknown type name 'ARWorldTrackingSessionConfiguration'
    ARWorldTrackingSessionConfiguration* config = [ARWorldTrackingSessionConfiguration new];
    ^
/Users/Jan/AR_GPS/Builds/PrevizAR_v00/Libraries/UnityARKitPlugin/Plugins/iOS/UnityARKit/NativeInterface/ARSessionNative.mm:689:52: error: use of undeclared identifier 'ARWorldTrackingSessionConfiguration'
    ARWorldTrackingSessionConfiguration* config = [ARWorldTrackingSessionConfiguration new];

/Users/Jan/AR_GPS/Builds/PrevizAR_v00/Libraries/UnityARKitPlugin/Plugins/iOS/UnityARKit/NativeInterface/ARSessionNative.mm:702:5: error: unknown type name 'ARWorldTrackingSessionConfiguration'
    ARWorldTrackingSessionConfiguration* config = [ARWorldTrackingSessionConfiguration new];
    ^
/Users/Jan/AR_GPS/Builds/PrevizAR_v00/Libraries/UnityARKitPlugin/Plugins/iOS/UnityARKit/NativeInterface/ARSessionNative.mm:702:52: error: use of undeclared identifier 'ARWorldTrackingSessionConfiguration'
    ARWorldTrackingSessionConfiguration* config = [ARWorldTrackingSessionConfiguration new];
                                                   ^
/Users/Jan/AR_GPS/Builds/PrevizAR_v00/Libraries/UnityARKitPlugin/Plugins/iOS/UnityARKit/NativeInterface/ARSessionNative.mm:712:5: error: unknown type name 'ARSessionConfiguration'
    ARSessionConfiguration* config = [ARSessionConfiguration new];
    ^
/Users/Jan/AR_GPS/Builds/PrevizAR_v00/Libraries/UnityARKitPlugin/Plugins/iOS/UnityARKit/NativeInterface/ARSessionNative.mm:712:39: error: use of undeclared identifier 'ARSessionConfiguration'
    ARSessionConfiguration* config = [ARSessionConfiguration new];

**Comment by SteSig** [comment]
Just update ARKIT from assetStore

**Comment by janvdh1111** [comment]
Thanks, that worked!!

**Comment by david-rhodes** [comment]
I'll update soon. Hoping the Unity `ARInterface` is available soon, so that this will also be compatible with ARCore (out of the box).
