### ISSUE TITLE
ARCore preview support?

### ISSUE THREAD

**Issue by tarakinsuide** [mapbox/mapbox-arkit-unity#33]
How to build this using ARCore? Any guidelines?

**Comment by wilhelmberg** [comment]
@tarakinsuide ARCore is already included in this project:
https://github.com/mapbox/mapbox-ar-unity/tree/develop/Assets/GoogleARCore

So it should just be `File -> Build Settings ... -> Android -> Build/Build And Run`

Do you get any errors?

Also make sure that you have a device that supports ARCore:
https://github.com/mapbox/mapbox-ar-unity#requirements

And that you have ARCore installed on your device:
https://play.google.com/store/apps/details?id=com.google.ar.core&hl=en

**Comment by tarakinsuide** [comment]
Do I need to change any camera settings? ARCoreCamera? I get blue screen with yellow dots. The phone camera is not rendering.

**Comment by wilhelmberg** [comment]
@tarakinsuide no you don't need to change anything, everything should work out of the box using `AutomaticWorldSynchronization` scene.


Did you follow the instructions?
https://github.com/mapbox/mapbox-ar-unity#usage

Especially 5. and 6.?

Afterwards you should see buildings overlayed. You could also tap the `LOG` button to get a sense on what's going on behind the scenes.

![image](https://user-images.githubusercontent.com/4549888/35095182-d8bb0cb4-fc47-11e7-88db-4b8d9861d61c.png)

**Comment by Crashthatch** [comment]
I could be wrong, but I think this repo has not been updated to support the latest arcore-preview-2 (released mid December). The google play link posted above (https://play.google.com/store/apps/details?id=com.google.ar.core&hl=en) is for arcore-preview-2 so will not work.

@tarakinsuide Try installing the old arcore-preview.apk (release 1) from the BOTTOM HALF of [this page ](https://github.com/google-ar/arcore-android-sdk/releases) and see if that helps.

This project should be updated to support ARCore-preview-2 (requires replacing https://github.com/mapbox/mapbox-ar-unity/tree/develop/Assets/UnityARInterface with the latest version from https://github.com/Unity-Technologies/experimental-ARInterface). There are some breaking changes, but from memory I think they're mostly in areas that mapbox-ar-unity doesn't use (eg. getCameraImage), so the upgrade should be fairly straighforward.
Relevant PRs to the UnityARInterface project are: https://github.com/Unity-Technologies/experimental-ARInterface/pull/18 and https://github.com/Unity-Technologies/experimental-ARInterface/pull/22

**Comment by wilhelmberg** [comment]
@Crashthatch yeah, thanks for pointing that out.
We have `ARCore SDK Preview` and *not* `ARCore SDK Preview 2`.

**Comment by wilhelmberg** [comment]
PR with latest `UnityARInterface` is up and will be merged soon: https://github.com/mapbox/mapbox-ar-unity/pull/36
