### ISSUE TITLE
Aligning AR to 3D Terrain

### ISSUE THREAD

**Issue by hectorsouthern** [mapbox/mapbox-arkit-unity#38]
Hi,

When using a terrain factory to produce the map, the terrain is much higher than the AR Root & Camera, so isn't visible, due to the 3D terrain being fixed at it's relative height in the real world, at the AR Camera being at 0,0,0.

![unity_2018-01-29_11-34-15](https://user-images.githubusercontent.com/5341944/35508546-b47128d0-04e8-11e8-861b-934a0d82a369.png)

I can't move the terrain down to 0,0,0, as it moves itself back up (I think the location provider is pulling it back up again), and I haven't found any way to move the AR components up to the same height.

Any ideas?

**Comment by Crashthatch** [comment]
I'm doing a similar thing: After the terrain has loaded I cast a Ray down from a point above the camera to find out how high the terrain is, then move the ARRoot element up so that the camera sits on the terrain (You can't move the camera directly as it's position will be overridden by ARController, so move its parent instead).

Run this repeatedly if you want to keep the camera on the terrain as it moves around.

```c#
using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Mapbox.Unity.Map;

public class keepOnTerrain : MonoBehaviour {
	public Transform _thingToMove;
	public float _heightAboveGround = 1;

	private void Start()
	{
		//Default to moving the object itself.
		if( _thingToMove == null )
		{
			_thingToMove = transform;
		}
	}

	void Update () {

		//TODO: Probably don't need to do this *every* frame.

		RaycastHit hit;
		//Simulate a ray from 1000m above the user to find out how far above/below the ground they are.
		int layerMask = (1 << LayerMask.NameToLayer("Map")); //Only intersect with the "map" layer.
		if (Physics.Raycast(this.transform.position + new Vector3(0, 1000, 0), Vector3.down, out hit, Mathf.Infinity, layerMask))
		{
			float distanceAboveGround = hit.distance - 1000;
			if (distanceAboveGround < _heightAboveGround*0.9 || distanceAboveGround > _heightAboveGround*1.1 || Math.Abs(distanceAboveGround - _heightAboveGround) > 1)
			{
				//Debug.Log(name+" is " + distanceAboveGround + "m above the ground. Moving "+ _thingToMove.name + "...");
				_thingToMove.transform.localPosition = new Vector3(_thingToMove.transform.localPosition.x, _thingToMove.transform.localPosition.y - distanceAboveGround + _heightAboveGround, _thingToMove.transform.localPosition.z);
			}
		}
	}

	public void setHeightAboveGround( float height)
	{
		_heightAboveGround = height;
	}
}
```
Add this to the MainCamera, and set thingToMove to ARRoot.

**Comment by nikhilsawlani** [comment]
Hi,
Thank you for the solution
how will we fix terrain or Map to remain on ground and it does not move like a still object, as it was shown in demo for the unite Austin 
Thanks

**Comment by hectorsouthern** [comment]
Hi,

Having used the code @Crashthatch suggested, there is definitely an issue with the terrain moving, especially if the device/camera moves vertically up and down. Perhaps a better way would be trying to move the terrain to match the height of the planes generated by ARCore/ARKit, as this is a stationary object aligned with the floor.

I'll look into this and see if I get anywhere.

**Comment by UtkarshRode12** [comment]
> I'm doing a similar thing: After the terrain has loaded I cast a Ray down from a point above the camera to find out how high the terrain is, then move the ARRoot element up so that the camera sits on the terrain (You can't move the camera directly as it's position will be overridden by ARController, so move its parent instead).
> 
> Run this repeatedly if you want to keep the camera on the terrain as it moves around.
> 
> ```cs
> using System;
> using System.Collections;
> using System.Collections.Generic;
> using UnityEngine;
> using Mapbox.Unity.Map;
> 
> public class keepOnTerrain : MonoBehaviour {
> 	public Transform _thingToMove;
> 	public float _heightAboveGround = 1;
> 
> 	private void Start()
> 	{
> 		//Default to moving the object itself.
> 		if( _thingToMove == null )
> 		{
> 			_thingToMove = transform;
> 		}
> 	}
> 
> 	void Update () {
> 
> 		//TODO: Probably don't need to do this *every* frame.
> 
> 		RaycastHit hit;
> 		//Simulate a ray from 1000m above the user to find out how far above/below the ground they are.
> 		int layerMask = (1 << LayerMask.NameToLayer("Map")); //Only intersect with the "map" layer.
> 		if (Physics.Raycast(this.transform.position + new Vector3(0, 1000, 0), Vector3.down, out hit, Mathf.Infinity, layerMask))
> 		{
> 			float distanceAboveGround = hit.distance - 1000;
> 			if (distanceAboveGround < _heightAboveGround*0.9 || distanceAboveGround > _heightAboveGround*1.1 || Math.Abs(distanceAboveGround - _heightAboveGround) > 1)
> 			{
> 				//Debug.Log(name+" is " + distanceAboveGround + "m above the ground. Moving "+ _thingToMove.name + "...");
> 				_thingToMove.transform.localPosition = new Vector3(_thingToMove.transform.localPosition.x, _thingToMove.transform.localPosition.y - distanceAboveGround + _heightAboveGround, _thingToMove.transform.localPosition.z);
> 			}
> 		}
> 	}
> 
> 	public void setHeightAboveGround( float height)
> 	{
> 		_heightAboveGround = height;
> 	}
> }
> ```
> 
> Add this to the MainCamera, and set thingToMove to ARRoot.

i was using similar logic to position the camera over  the terrain in a non-AR project but my raycasts dont seem to detect anything. Meshes generated by mapbox are not detected by raycasts it seems
