### ISSUE TITLE
AutomaticSynchronizationContext example not working

### ISSUE THREAD

**Issue by lightbringer** [mapbox/mapbox-arkit-unity#39]
Hi,
I just started playing around with your project and had a look at the example scenes, modified them, etc.
It looks to me that the _LocationProvider_ property of _SimpleAutomaticSynchronizationContextBehaviour_ is actually never set. Instead the getter just pulls it out of the factory singleton. However, the behaviour never actually subscribes the wrapped _SynchronizationContext_ to the _OnLocationUpdated_ event like the setter does. Hence the location is never updated.

I solved this by adding
``  _locationProvider.OnLocationUpdated += LocationProvider_OnLocationUpdated;``
to the property's setter. 

Is this by design, i.e. did I miss something, or is the example actually broken?

**Comment by wilhelmberg** [comment]
@lightbringer are you testing in Editor (with Unity Remote?) or directly on device?
There's a little bug when running in Editor but on device it should work as expected.

You might want to double check if the correct location providers are assigned:
![image](https://user-images.githubusercontent.com/4549888/36030233-a95f1e7c-0da6-11e8-87e8-39feaea9330f.png)

**Comment by lightbringer** [comment]
The example scene was completely wrong on my device, so I investigated and tested it in the editor (without the remote). Did a code search and nothing came up that called the setter or registered the callback. Hence my breakpoint in _LocationProvider_OnLocationUpdated_ was never triggered.

The location providers were all set up (I tried this with a fresh clone of the repo).
Before doing this change, I also didn't get any messages from the sync context regarding GPS accuracy in the console on the device.

**Comment by wilhelmberg** [comment]
> Hence my breakpoint in LocationProvider_OnLocationUpdated was never triggered.

Events are filtered by several parameters, eg `Desired Accuracy` which are passed on to Unity's [`LocationService.Start()`](https://docs.unity3d.com/ScriptReference/LocationService.Start.html)

> I also didn't get any messages from the sync context regarding GPS accuracy in the console on the device.

In case you are in an area with less than perfect GPS reception you might want to increase `Desired Accuracy` to maybe `20` or even higher (when inside) and maybe reduce `Update Distance` a bit:

![image](https://user-images.githubusercontent.com/4549888/36031179-29a6b312-0daa-11e8-9977-0dd1538ccc5b.png)

And also increase `Desired Accuracy` here:

![image](https://user-images.githubusercontent.com/4549888/36031129-008940da-0daa-11e8-8019-54d4ca21e67a.png)

**Comment by lightbringer** [comment]
I'm playing with all these values now, and am getting messages regarding dropped GPS positions etc. Fair enough.

But out-of-the box, the callback simply never got registered. Where is _SimpleAutomaticSynchronizationContextBehaviour#LocationProvider_OnLocationUpdated_ to be hooked up with the LocationProvider? The only place I found was _SimpleAutomaticSynchronizationContextBehaviour#LocationProvider_set_ and I'm unsure which object is supposed to set that one. A code search through the project didn't return anything.

**Comment by david-rhodes** [comment]
The context itself (not the behaviour wrapper) does not need the provider. It just needs "nodes." In the behaviour, location provider is acquired lazily here: https://github.com/mapbox/mapbox-ar-unity/blob/develop/Assets/Mapbox/Unity/Ar/SimpleAutomaticSynchronizationContextBehaviour.cs#L101. 

In the method that is invoked as a result of location update, the context gets nodes appended to it here: https://github.com/mapbox/mapbox-ar-unity/blob/develop/Assets/Mapbox/Unity/Ar/SimpleAutomaticSynchronizationContextBehaviour.cs#L144

**Comment by wilhelmberg** [comment]
@lightbringer in case you are getting a lot of dropped GPS positions, you might want to try **switching wifi off**.

On my Samsung S8 Unity reported very bad GPS signal (41m accuracy) whereas the devices itself reported 5m.

After switching wifi off both values were in sync.

![image](https://user-images.githubusercontent.com/4549888/36442062-cd99bd66-1674-11e8-8632-c5ff993a3515.png)

**Comment by wilhelmberg** [comment]
Stale.
