### ISSUE TITLE
Update Mapbox SDK to v1.2.0

### ISSUE THREAD

**Issue by david-rhodes** [mapbox/mapbox-arkit-unity#4]
Lots of cool upgrades and abstractions that might be helpful.

**Comment by thehen** [comment]
Is there an ETA on this? Is it recommended to use v1.0.0 in the meantime?

**Comment by david-rhodes** [comment]
@thehen TBH, I was waiting for Unity to release the ARInterface that they presented at Unite Austin so that I could tackle both tasks at the same time. But perhaps I'll just do this soon--shouldn't take too long.

**Comment by thehen** [comment]
@david-rhodes Ah that would be fab, thanks! Is there anywhere I can find more info on the ARInterface as well, the only reference I could find to it is your open issue! :D

**Comment by david-rhodes** [comment]
It was mentioned during an AR talk presented by Unity employees. They said that it would be released in two weeks, so I expect it any day now. I'll post a link to the talk once Unity uploads it.

**Comment by thehen** [comment]
@david-rhodes awesome, thanks!

**Comment by david-rhodes** [comment]
Done #11
