### ISSUE TITLE
Object Syncing

### ISSUE THREAD

**Issue by iiidefektiii** [mapbox/mapbox-arkit-unity#41]
I'm not really sure where to ask this so I will ask here. So far everything in this package works great. They only issue I am having is when viewing the AR from street level and have a map in the corner to see my position is that it is putting me in the correct location on the map but in the real world street view it takes more then a block for the objects to slide into position. 

Is there anyway to improve accuracy over a shorter distance? I understand the GPS takes a few meters to calculate position but it seems like it takes a lot longer then when it syncs on the map view.

**Comment by wilhelmberg** [comment]
@iiidefektiii we are currently transferring this repo into the main `mapbox-unity-sdk`.
After that improving accuracy faster is one of our top priorities.

I've carried this ticket over to https://github.com/mapbox/mapbox-unity-sdk/issues/561
