### ISSUE TITLE
Multi-user example

### ISSUE THREAD

**Issue by thomasgauthier** [mapbox/mapbox-arkit-unity#42]
Is there any demo scene to test out multiplayer AR? I'm thinking specifically about this demo https://blog.mapbox.com/multi-user-ar-experience-1a586f40b2ce.

**Comment by thespacemaker** [comment]
any updates on this?

**Comment by vahidreza** [comment]
hey guys
really need this.
any update?

**Comment by jordy-isaac** [comment]
@thespacemaker @vahidreza This repo has been deprecated as we've merged all the AR files into the core SDK. This is the main and only repo now: https://github.com/mapbox/mapbox-unity-sdk/issues

As for multi player we don't have an example for it, but you'll need some sort of networking implemented which would be up to you. I've used Photon with success in the past and there are various other networking tools out there that could work for multi player AR. 

If you need additional help please cut a ticket on the other repo. Thanks!

**Comment by stacK5555** [comment]
Even I want to achieve this with Photon. Any help?
