### ISSUE TITLE
Building prefabs on maps from Mapbox for Unity3d

### ISSUE THREAD

**Issue by SergKredo** [mapbox/mapbox-arkit-unity#47]
Everybody, Hi. I have a problem. Could you help me to solve it. I want to create a third-party objects-prefabs on map from Mapbox to used Unity3d. After adding prefabs and then scaling and moving the map my prefabs are deleted. If you return to the original position on the map again and the scale of these objects-prefabs is already gone. How can I solve this problem so that third-party prefabs in Mapbox for Unity3d remain on the map when scaling and moving the map itself? Thank.

**Comment by TevfikUfuk** [comment]
Did you make your prefabs the child of map?

**Comment by SergKredo** [comment]
Thank you. I tried to do so does not help.
