### ISSUE TITLE
Investigate map matching to assist in stabilizing traces

### ISSUE THREAD

**Issue by david-rhodes** [mapbox/mapbox-arkit-unity#7]
Standard technique used in popular mapping applications to clean up noisy GPS results. See: https://www.mapbox.com/api-documentation/#map-matching

**Comment by david-rhodes** [comment]
Reference: https://github.com/mapbox/mapbox-unity-sdk/pull/302

**Comment by david-rhodes** [comment]
Map matching is now included in this repo as part of Mapbox Unity SDK 1.2 (published from `develop` branch).

**Comment by david-rhodes** [comment]
Note for reference: a directions query could also be used to compute an absolute heading.

**Comment by wilhelmberg** [comment]
continued at https://github.com/mapbox/mapbox-unity-sdk/issues/554
