### ISSUE TITLE
Implement GPS filtering

### ISSUE THREAD

**Issue by david-rhodes** [mapbox/mapbox-arkit-unity#8]
Based on physical improbabilities. This will assist in more stable traces, which will lead to better heading results.

**Comment by david-rhodes** [comment]
Reference: https://github.com/mapbox/mapbox-unity-sdk/pull/394

Edit: this could also be used to provide bearing (heading), rather than computing manually.

**Comment by wilhelmberg** [comment]
continued at https://github.com/mapbox/mapbox-unity-sdk/issues/553
