### ISSUE TITLE
Unity Cloud Build Issue

### ISSUE THREAD

**Issue by evans-ioe** [mapbox/mapbox-arkit-unity#9]
I work using Windows and am developing for iOS using Unity Cloud Build.
None of the builds have completed successfully.
I cloned this repo and replaced the UnityARKitPlugin folder with the latest from the [bitbucket](https://bitbucket.org/Unity-Technologies/unity-arkit-plugin) repo.

This is the log from the latest build:

https://pastebin.com/VVEuQtmg

I've left out a number of warnings, but can include them if necessary.

Can anyone figure this out? Is it ok to replace the UnityARKitPlugin folder with code from the bitbucket repo?

**Comment by evans-ioe** [comment]
On the forum it's suggested that Xcode 9 beta 5 be used. Could the issue be that Unity cloud build doesn't use beta versions of xcode?

https://forum.unity.com/threads/arkit-support-for-ios-via-unity-arkit-plugin.474385/page-24#post-3187178

https://forum.unity.com/threads/is-xcode-9-beta-support-coming-soon.479981/

**Comment by david-rhodes** [comment]
> Could the issue be that Unity cloud build doesn't use beta versions of xcode?

Correct. That said, now that Xcode 9 is out of beta, it may work? Just ensure you use the latest unity version (2017.2) and explicitly choose your xcode version. 

Do you have any errors in your local unity editor?

**Comment by evans-ioe** [comment]
Thanks for the prompt reply!

I'll try your recommendations and let you know if it works.

Also, there are no errors in the local editor.

**Comment by evans-ioe** [comment]
Sorry for my silence.
I still haven't gotten the project to build successfully on Unity Cloud, but I managed to get access to a Macbook and commit 8c9a49bd6219aa3b9eee64307540f25a59cafdb2 built successfully using xCode. Thanks for your help and your time!

**Comment by david-rhodes** [comment]
Yeah--sorry about that! Unity Cloud Build is still limited in so many ways. Hopefully this pipeline works in a few weeks. Glad you got a build, though!
